---
abstract: 'show warnings with sigil prefix'
author:
  - 'Kuniyoshi Kouji <kuniyoshi@cpan.org>'
build_requires:
  Test::More: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Sigil
requires:
  Class::Accessor: 0
  Class::Singleton: 0
  Readonly: 0
version: 1.02
